#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $script_dir)
db_dir=$repo_dir/_db

if [ ! -d $db_dir ]; then
    mkdir -p $db_dir
fi

mongod --dbpath $db_dir
