#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $script_dir)
env_path=$repo_dir/.env

if [ -e $env_path ]; then
  temp_ifs=$IFS
  IFS=$' '
  export $(cat $env_path | xargs)
  IFS=$temp_ifs
fi

#SOME_VAR=${SOME_VAR:-default}

cd $repo_dir
REACT_APP_API_ROOT=$HS_REALWORLD_FRONTEND_API_ROOT \
    _frontend/script/dev
